#filebeat.modules:
#- module: nginx
#- module: elasticsearch
# will use logstash pipeline

filebeat.inputs: 
- input_type: log 
  type: log 
  enabled: true 
  paths: 
    - /opt/dionaea/var/lib/dionaea/dionaea.json*
  encoding: plain 
  fields: 
    document_type: dionaea 

registry_file: /var/lib/filebeat/registry 

output.logstash: 
  hosts: ["logstash:5044"]

shipper: 

logging: 
  to_syslog: false 
  to_files: true 
  files: 
    path: /var/log/filebeat/ 
    name: mybeat 
    rotateeverybytes: 10485760 # = 10MB 
    keepfiles: 7 
  level: info