
# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:7.12.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

#COPY logstash-cowrie.conf /etc/logstash/conf.d/logstash-cowrie.conf